nelmio_api_doc:
    documentation:
        info:
            title: "Order Service API"
            description: "Документация для микросервиса заказов"
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: Order, type: App\Entity\Order }
            - { alias: OrderItem, type: App\Entity\OrderItem }
            - { alias: OrderRequest, type: App\DTO\OrderRequest }
            - { alias: OrderItemRequest, type: App\DTO\OrderItemRequest }
            - { alias: UpdateOrderRequest, type: App\DTO\UpdateOrderRequest }
            - { alias: SearchByProductIdRequest, type: App\DTO\SearchByProductIdRequest }
