controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_docs:
    path: /api/docs.json
    controller: App\Controller\ApiDocController::aggregateDocs
